"""initial

Revision ID: 3856af4fd131
Revises: 
Create Date: 2026-04-17 17:13:40.699920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3856af4fd131'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('generation_name', sa.String(), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Generation_id'), 'Generation', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('specs', sa.String(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_Generation_id'), table_name='Generation')
    op.drop_table('Generation')
    # ### end Alembic commands ###
