"""add codes to generation

Revision ID: f37996bfca55
Revises: 3856af4fd131
Create Date: 2026-09-25 17:06:34.639593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37996bfca55'
down_revision: Union[str, Sequence[str], None] = '3856af4fd131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Generation', sa.Column('mark_code', sa.String(), nullable=True))
    op.add_column('Generation', sa.Column('model_code', sa.String(), nullable=True))
    op.add_column('Generation', sa.Column('gen_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Generation', 'gen_code')
    op.drop_column('Generation', 'model_code')
    op.drop_column('Generation', 'mark_code')
    # ### end Alembic commands ###
